# Generated by Django 3.0 on 2023-09-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=32, verbose_name='ְ职位名称')),
                ('area', models.CharField(max_length=32, verbose_name='地区')),
                ('salary', models.CharField(max_length=32, verbose_name='薪水')),
                ('tag', models.CharField(max_length=32, verbose_name='标签')),
                ('ability', models.CharField(max_length=32, verbose_name='能力要求')),
                ('company', models.CharField(max_length=32, verbose_name='公司名字')),
                ('welfare', models.CharField(max_length=128, verbose_name='福利待遇')),
                ('link', models.CharField(max_length=128, verbose_name='详情链接')),
            ],
        ),
    ]
